### ISSUE TITLE
GPU temperature

### ISSUE THREAD

**Issue by ruzickap** [tkeech1/rpi-exporter#1]
Would it be possible to add also the RPi GPU temperature to rpi-exporter ?

GPU temperature can be found by running:

```bash
/opt/vc/bin/vcgencmd measure_temp
```

Thanks...

**Comment by tkeech1** [comment]
@ruzickap 
This project uses the [node_exporter](https://github.com/prometheus/node_exporter) from Prometheus.  Nvidia also has a project that includes [GPU monitoring tools](https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm) that might be helpful. Best of luck.

**Comment by ruzickap** [comment]
Sorry - I put this question to wrong project.
Please ignore...
